## This is an ubuntu image for situations that require Python and R and possibly other softwares
## Start from this Docker image
FROM ubuntu

## Install R in Docker image
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y r-base